# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:
  zookeeper-base:
    image: hyperledger/fabric-zookeeper:x86_64-1.0.6
    restart: always
    tty: true
    expose:
      - '2181'
      - '2888'
      - '3888'

  kafka-base:
    # official repo doesn't have latest tag, however, kafka changes version recently
    #image: yeasy/hyperledger-fabric-kafka:0.10.2.0
    image: hyperledger/fabric-kafka:x86_64-1.0.6
    restart: always
    tty: true
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
    expose:
      - '9092'

  #orderer-base: