# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer0.bgiblockchain.com:
    container_name: orderer0
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer0.bgiblockchain.com
    depends_on:
      - kafka0.bgiblockchain.com
      - kafka1.bgiblockchain.com
      - kafka2.bgiblockchain.com
      - kafka3.bgiblockchain.com

  orderer2.bgiblockchain.com:
    container_name: orderer2
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer2.bgiblockchain.com
    depends_on:
      - kafka0.bgiblockchain.com
      - kafka1.bgiblockchain.com
      - kafka2.bgiblockchain.com
      - kafka3.bgiblockchain.com

  peer0.health.bgiblockchain.com:
    container_name: peer0
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.health.bgiblockchain.com
    depends_on:
      - orderer0.bgiblockchain.com

  peer1.health.bgiblockchain.com:
    container_name: peer1
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.health.bgiblockchain.com

  peer2.health.bgiblockchain.com:
    container_name: peer2
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.health.bgiblockchain.com

  peer3.health.bgiblockchain.com:
    container_name: peer3
    extends:
      file:  base/docker-compose-base.yaml
      service: peer3.health.bgiblockchain.com

  cli2:
    container_name: cli2
    extends:
      file:  base/peer-base.yaml
      service: cli-base
    environment:
      - CORE_PEER_ID=cli2
      - CORE_PEER_ADDRESS=peer2.health.bgiblockchain.com:7251
      - CORE_PEER_LOCALMSPID=HealthMSP
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/health.bgiblockchain.com/peers/peer2.health.bgiblockchain.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/health.bgiblockchain.com/peers/peer2.health.bgiblockchain.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/health.bgiblockchain.com/peers/peer2.health.bgiblockchain.com/tls/ca.crt
    #command: /bin/bash -c './scripts/script_kafka.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /bgi/blockchain_data/cli2/pro/:/opt/gopath/src/github.com/hyperledger/fabric/peer
  #      - /usr/bin/telnet:/usr/bin/telnet
    depends_on:
      - orderer0.bgiblockchain.com
      - orderer2.bgiblockchain.com
      - peer0.health.bgiblockchain.com
      - peer1.health.bgiblockchain.com
      - peer2.health.bgiblockchain.com
      - peer3.health.bgiblockchain.com


# ZooKeeper services, at least 3 nodes
  zookeeper0.bgiblockchain.com:
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper0.bgiblockchain.com

  zookeeper1.bgiblockchain.com:
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper1.bgiblockchain.com

  zookeeper2.bgiblockchain.com:
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper2.bgiblockchain.com

# Kafka services, at least 4 node to tolerant work with 1 node failure
  kafka0.bgiblockchain.com:
    extends:
      file: base/docker-compose-base.yaml
      service: kafka0.bgiblockchain.com
    depends_on:
      - zookeeper0.bgiblockchain.com
      - zookeeper1.bgiblockchain.com
      - zookeeper2.bgiblockchain.com

  kafka1.bgiblockchain.com:
    extends:
      file: base/docker-compose-base.yaml
      service: kafka1.bgiblockchain.com
    depends_on:
      - zookeeper0.bgiblockchain.com
      - zookeeper1.bgiblockchain.com
      - zookeeper2.bgiblockchain.com

  kafka2.bgiblockchain.com:
    extends:
      file: base/docker-compose-base.yaml
      service: kafka2.bgiblockchain.com
    depends_on:
      - zookeeper0.bgiblockchain.com
      - zookeeper1.bgiblockchain.com
      - zookeeper2.bgiblockchain.com

  kafka3.bgiblockchain.com:
    extends:
      file: base/docker-compose-base.yaml
      service: kafka3.bgiblockchain.com
    depends_on:
      - zookeeper0.bgiblockchain.com
      - zookeeper1.bgiblockchain.com
      - zookeeper2.bgiblockchain.com
