# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  ca0:
    image: hyperledger/fabric-ca
    hostname: ca.health.bgiblockchain.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.health.bgiblockchain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.health.bgiblockchain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/health.bgiblockchain.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.health.bgiblockchain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.health.bgiblockchain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/health.bgiblockchain.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2

  orderer0.bgiblockchain.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer0.bgiblockchain.com
    container_name: orderer0.bgiblockchain.com

  peer2.health.bgiblockchain.com:
    container_name: peer2.health.bgiblockchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.health.bgiblockchain.com

  peer1.health.bgiblockchain.com:
    container_name: peer1.health.bgiblockchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.health.bgiblockchain.com

  peer2.health.bgiblockchain.com:
    container_name: peer2.health.bgiblockchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.health.bgiblockchain.com

  peer0.health.bgiblockchain.com:
    container_name: peer0.health.bgiblockchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.health.bgiblockchain.com
