# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:
  env-base:
    #env_file: .env
    #environment:
      #- PRODUCTIONPATH=/bgi/bgiblockchain
      #- PRODUCTIONPATH=../bgiblockchain
    logging:
      options:
        max-size: '100m'
        max-file: '100'    
      driver: json-file
      #driver: fluentd  
#    volumes:
#      - '/usr/bin/telnet:/usr/bin/telnet'
#      - '/usr/bin/ping:/usr/bin/ping'
#    extra_hosts:
      #测试环境

    #  - "zookeeper0.bgiblockchain.com:192.168.31.103"
    #  - "zookeeper1.bgiblockchain.com:192.168.31.104"
    #  - "zookeeper2.bgiblockchain.com:192.168.31.60"
    #  - "kafka0.bgiblockchain.com:192.168.31.103"
    #  - "kafka1.bgiblockchain.com:192.168.31.104"
    #  - "kafka2.bgiblockchain.com:192.168.31.60"
    #  - "kafka3.bgiblockchain.com:192.168.31.103"
    #  - "orderer0.bgiblockchain.com:192.168.31.103"
    #  - "orderer1.bgiblockchain.com:192.168.31.104"
    #  - "orderer2.bgiblockchain.com:192.168.31.60"
    #  - "peer0.health.bgiblockchain.com:192.168.31.103"
    #  - "peer1.health.bgiblockchain.com:192.168.31.103"
    #  - "peer2.health.bgiblockchain.com:192.168.31.103"
    #  - "peer3.health.bgiblockchain.com:192.168.31.103"
    #  - "peer4.health.bgiblockchain.com:192.168.31.104"
    #  - "peer5.health.bgiblockchain.com:192.168.31.104"
    #  - "peer6.health.bgiblockchain.com:192.168.31.104"
    #  - "peer7.health.bgiblockchain.com:192.168.31.104"
    #  - "peer8.health.bgiblockchain.com:192.168.31.60"
    #  - "peer9.health.bgiblockchain.com:192.168.31.60"
    #  - "peer10.health.bgiblockchain.com:192.168.31.60"
    #  - "peer11.health.bgiblockchain.com:192.168.31.60"
    #  - "peer16.health.bgiblockchain.com:172.29.114.229"
    #  - "peer17.health.bgiblockchain.com:172.29.114.229"
    #  - "peer18.health.bgiblockchain.com:172.29.114.229"
    #  - "peer19.health.bgiblockchain.com:172.29.114.229"

  zookeeper-base:
    image: hyperledger/fabric-zookeeper
    extends: env-base
    restart: always
    tty: true
    #ports:
    #  - '2181:2181'
    #  - '2888:2888'
    #  - '3888:3888'

  kafka-base:
    # official repo doesn't have latest tag, however, kafka changes version recently
    #image: yeasy/hyperledger-fabric-kafka:0.10.2.0
    image: hyperledger/fabric-kafka
    extends: env-base
    restart: always
    tty: true
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
    #expose:
    #  - '9092'

  orderer-base:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    extends: env-base
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - GODEBUG=netdns=go
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      # kafka
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer

  peer-base:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    extends: env-base
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=e2ecli_default
      #- CORE_LOGGING_LEVEL=ERROR
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_BGITLS=true
      - CORE_PEER_BGICAFILE=/etc/hyperledger/fabric/tls/tlsca/tlsca.bgiblockchain.com-cert.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - GODEBUG=netdns=go
      - CORE_PEER_GRPCTLS=true
      #- CORE_PEER_GRPCTLS=true
      - CORE_PEER_GRPCCERTFILE=/etc/hyperledger/fabric/tls/bgitls/grpcserver.crt
      - CORE_PEER_GRPCKEYFILE=/etc/hyperledger/fabric/tls/bgitls/grpcserver.key
    volumes:
      - /opt/gopath/src/github.com/hyperledger/fabric/bgi_client_health/backup/grpctls:/etc/hyperledger/fabric/tls/bgitls
      - ../crypto-config/ordererOrganizations/bgiblockchain.com/tlsca/:/etc/hyperledger/fabric/tls/tlsca
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c 'peer node start'


  cli-base:
    image: hyperledger/fabric-tools:$IMAGE_TAG
    extends: env-base
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_BGITLS=true
      - CORE_PEER_BGICAFILE=/etc/hyperledger/fabric/tls/tlsca/tlsca.bgiblockchain.com-cert.pem      
      - CORE_PEER_LOCALMSPID=HealthMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/health.bgiblockchain.com/users/Admin@health.bgiblockchain.com/msp
      - CORE_PEER_MULTITHCNT=6
      - CORE_PEER_DEFAULTLISADDRIP=0.0.0.0
      - CORE_PEER_DEFAULTLISADDRPORT=9000
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - ../examples/chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ../crypto-config/ordererOrganizations/bgiblockchain.com/tlsca/:/etc/hyperledger/fabric/tls/tlsca
